import type { Puzzle } from './types';
import { PENGUINS_FILE, PENGUINS_SETUP } from './datasets';

// Each puzzle is code an "AI assistant" wrote for a task, with exactly one bug. The learner first clicks
// the line they think is wrong, then fixes it. The checker proves the buggy code fails the tests, the
// fixed code passes, and only the bugLines differ.

const SAMPLE_PENGUINS = `penguins = [
    {"species": "Gentoo", "body_mass_g": 5400},
    {"species": "Gentoo", "body_mass_g": 4750},
    {"species": "Adelie", "body_mass_g": 5100},
    {"species": "Chinstrap", "body_mass_g": 3700},
    {"species": "Gentoo", "body_mass_g": 5650},
]
`;

export const PUZZLES: Puzzle[] = [
  {
    id: 'pz-assign-compare',
    title: 'One equals too few',
    rating: 400,
    concepts: ['if', 'comparison'],
    task: 'Print "Found an Adelie" if species is "Adelie".',
    buggy: 'species = "Adelie"\nif species = "Adelie":\n    print("Found an Adelie")\n',
    fixed: 'species = "Adelie"\nif species == "Adelie":\n    print("Found an Adelie")\n',
    bugLines: [2],
    tests: 'assert output.strip() == "Found an Adelie", "It should print: Found an Adelie"',
    explain: '`=` stores a value; `==` compares two values. An `if` needs a comparison, so Python raises a SyntaxError.',
  },
  {
    id: 'pz-concat-number',
    title: 'Text plus a number',
    rating: 450,
    concepts: ['strings', 'types'],
    task: 'Print "Total penguins: 344".',
    buggy: 'count = 344\nprint("Total penguins: " + count)\n',
    fixed: 'count = 344\nprint(f"Total penguins: {count}")\n',
    bugLines: [2],
    tests: 'assert output.strip() == "Total penguins: 344", "It should print: Total penguins: 344"',
    explain: "You can't `+` a string and a number. Use an f-string, or convert with `str(count)`.",
  },
  {
    id: 'pz-dash-divider',
    title: 'A divider line',
    rating: 500,
    concepts: ['strings', 'types'],
    task: 'Print a divider made of 20 dashes.',
    buggy: 'width = "20"\nprint("-" * width)\n',
    fixed: 'width = 20\nprint("-" * width)\n',
    bugLines: [1],
    tests: 'assert output.strip() == "-" * 20, "It should print 20 dashes."',
    explain: 'A string can be repeated by a number (`"-" * 20`), but not by another string. The width was stored as text.',
  },
  {
    id: 'pz-average-floor',
    title: 'Rounded down too soon',
    rating: 550,
    concepts: ['maths'],
    task: 'Print the exact average of three masses.',
    buggy: 'masses = [3750, 3800, 3300]\naverage = sum(masses) // len(masses)\nprint(average)\n',
    fixed: 'masses = [3750, 3800, 3300]\naverage = sum(masses) / len(masses)\nprint(average)\n',
    bugLines: [2],
    tests: 'assert abs(average - 10850 / 3) < 1e-9, "The average should be about 3616.67, not rounded down."',
    explain: '`//` divides and rounds down to a whole number. For an exact average use `/`.',
  },
  {
    id: 'pz-last-index',
    title: 'One past the end',
    rating: 550,
    concepts: ['lists', 'indexing'],
    task: 'Get the last mass in the list.',
    buggy: 'masses = [3750, 3800, 3250, 3450]\nlast = masses[len(masses)]\nprint(last)\n',
    fixed: 'masses = [3750, 3800, 3250, 3450]\nlast = masses[len(masses) - 1]\nprint(last)\n',
    bugLines: [2],
    tests: 'assert last == 3450, "last should be 3450, the final item."',
    explain: 'Indexes start at 0, so the last index is `len(masses) - 1`. Even simpler: `masses[-1]`.',
  },
  {
    id: 'pz-range-stop',
    title: 'Counting to ten',
    rating: 600,
    concepts: ['loops', 'range'],
    task: 'Print the numbers 1 to 10.',
    buggy: 'for n in range(1, 10):\n    print(n)\n',
    fixed: 'for n in range(1, 11):\n    print(n)\n',
    bugLines: [1],
    tests: 'assert lines == [str(n) for n in range(1, 11)], "It should print 1 to 10, including 10."',
    explain: "`range()` never includes its stop number, so counting to 10 needs `range(1, 11)`.",
  },
  {
    id: 'pz-key-case',
    title: 'Case sensitive',
    rating: 600,
    concepts: ['dictionaries'],
    task: "Print the penguin's mass.",
    buggy: 'penguin = {"species": "Gentoo", "mass_g": 5000}\nprint(penguin["Mass_g"])\n',
    fixed: 'penguin = {"species": "Gentoo", "mass_g": 5000}\nprint(penguin["mass_g"])\n',
    bugLines: [2],
    tests: 'assert output.strip() == "5000", "It should print 5000."',
    explain: 'Dictionary keys are case-sensitive: `"Mass_g"` and `"mass_g"` are different keys, so this raises a KeyError.',
  },
  {
    id: 'pz-print-in-loop',
    title: 'Too much output',
    rating: 650,
    concepts: ['loops', 'indentation'],
    task: 'Add up the masses and print the total once, at the end.',
    buggy: 'total = 0\nfor m in [3750, 3800, 3250]:\n    total += m\n    print(total)\n',
    fixed: 'total = 0\nfor m in [3750, 3800, 3250]:\n    total += m\nprint(total)\n',
    bugLines: [4],
    tests: 'assert lines == ["10800"], "It should print one line: the final total, 10800."',
    explain: 'Indentation decides what is inside the loop. The indented `print` ran on every pass, not once at the end.',
  },
  {
    id: 'pz-strip-unsaved',
    title: 'Tidied and forgotten',
    rating: 700,
    concepts: ['strings', 'methods'],
    task: 'Print the island name in square brackets, without the extra spaces: [Biscoe]',
    buggy: 'island = "  Biscoe  "\nisland.strip()\nprint(f"[{island}]")\n',
    fixed: 'island = "  Biscoe  "\nisland = island.strip()\nprint(f"[{island}]")\n',
    bugLines: [2],
    tests: 'assert output.strip() == "[Biscoe]", "It should print [Biscoe] with no spaces inside the brackets."',
    explain: "Strings can't be changed in place. `.strip()` returns a new string, which has to be stored: `island = island.strip()`.",
  },
  {
    id: 'pz-overwrite-total',
    title: 'The total that forgets',
    rating: 700,
    concepts: ['loops', 'accumulator'],
    task: 'Add up all the masses.',
    buggy: 'masses = [3750, 3800, 3250]\ntotal = 0\nfor m in masses:\n    total = m\nprint(total)\n',
    fixed: 'masses = [3750, 3800, 3250]\ntotal = 0\nfor m in masses:\n    total += m\nprint(total)\n',
    bugLines: [4],
    tests: 'assert total == 10800, f"total should be 10800, but it is {total}."',
    explain: '`total = m` replaces the total each time, so it ends up as the last mass. `total += m` adds to it.',
  },
  {
    id: 'pz-percent-floor',
    title: 'Zero percent?',
    rating: 750,
    concepts: ['maths'],
    task: 'Work out what percentage of 152 penguins are heavy, if 40 of them are.',
    buggy: 'heavy = 40\ntotal = 152\npercent = heavy // total * 100\nprint(round(percent, 1))\n',
    fixed: 'heavy = 40\ntotal = 152\npercent = heavy / total * 100\nprint(round(percent, 1))\n',
    bugLines: [3],
    tests: 'assert round(percent, 1) == 26.3, f"The answer should be about 26.3%, but it is {percent}."',
    explain: '`40 // 152` rounds down to 0 before the multiplication. Use `/` so the fraction survives.',
  },
  {
    id: 'pz-count-keyerror',
    title: 'Counting from nothing',
    rating: 800,
    concepts: ['dictionaries', 'counting'],
    task: 'Count how many times each species was seen.',
    setup: 'seen = ["Adelie", "Gentoo", "Adelie"]\n',
    given: '`seen` is already set to `["Adelie", "Gentoo", "Adelie"]`.',
    buggy: 'counts = {}\nfor s in seen:\n    counts[s] += 1\nprint(counts)\n',
    fixed: 'counts = {}\nfor s in seen:\n    counts[s] = counts.get(s, 0) + 1\nprint(counts)\n',
    bugLines: [3],
    tests: 'assert counts == {"Adelie": 2, "Gentoo": 1}, f"Expected Adelie 2, Gentoo 1, but got {counts}."',
    explain: '`counts[s] += 1` has to read `counts[s]` first, which fails with a KeyError for a new species. `.get(s, 0)` starts new ones at 0.',
  },
  {
    id: 'pz-or-and',
    title: 'Too generous',
    rating: 800,
    concepts: ['conditions', 'records'],
    task: 'Count the Gentoo penguins that weigh over 5000 g.',
    setup: SAMPLE_PENGUINS,
    given: '`penguins` is a list of 5 sample penguins, each a dictionary with `"species"` and `"body_mass_g"`.',
    buggy: 'count = 0\nfor p in penguins:\n    if p["species"] == "Gentoo" or p["body_mass_g"] > 5000:\n        count += 1\nprint(count)\n',
    fixed: 'count = 0\nfor p in penguins:\n    if p["species"] == "Gentoo" and p["body_mass_g"] > 5000:\n        count += 1\nprint(count)\n',
    bugLines: [3],
    tests: 'assert count == 2, f"Only 2 penguins are both Gentoo and over 5000 g, but count is {count}."',
    explain: 'Both conditions must be true, so it needs `and`. With `or`, every Gentoo and every heavy penguin was counted.',
  },
  {
    id: 'pz-none-sum',
    title: 'Adding nothing',
    rating: 900,
    concepts: ['None', 'real data'],
    task: 'Add up the body mass of every penguin in the real dataset, skipping missing values.',
    setup: PENGUINS_SETUP,
    given: '`penguins` is the full real dataset: 344 dictionaries, where missing values are `None`.',
    data: [PENGUINS_FILE],
    buggy: 'total = 0\nfor p in penguins:\n    if p["body_mass_g"] is None:\n        total += p["body_mass_g"]\nprint(total)\n',
    fixed: 'total = 0\nfor p in penguins:\n    if p["body_mass_g"] is not None:\n        total += p["body_mass_g"]\nprint(total)\n',
    bugLines: [3],
    tests: 'assert total == sum(p["body_mass_g"] for p in penguins if p["body_mass_g"] is not None), "total should be the sum of all recorded masses."',
    explain: 'The condition was backwards: it only tried to add the missing values (None), which raises a TypeError. It needs `is not None`.',
  },
  {
    id: 'pz-max-from-zero',
    title: 'The warmest winter day',
    rating: 900,
    concepts: ['loops', 'maximum'],
    task: 'Find the warmest temperature in a week of Antarctic winter readings (°C).',
    buggy: 'temps = [-12.5, -8.0, -15.2, -9.1]\nwarmest = 0\nfor t in temps:\n    if t > warmest:\n        warmest = t\nprint(warmest)\n',
    fixed: 'temps = [-12.5, -8.0, -15.2, -9.1]\nwarmest = temps[0]\nfor t in temps:\n    if t > warmest:\n        warmest = t\nprint(warmest)\n',
    bugLines: [2],
    tests: 'assert warmest == -8.0, f"The warmest reading is -8.0, but got {warmest}."',
    explain: 'Starting at 0 only works if some value is above 0. Every reading here is negative, so none beat 0. Start from the first item.',
  },
  {
    id: 'pz-elif-direction',
    title: 'Size categories',
    rating: 950,
    concepts: ['if', 'elif'],
    task: 'Label a penguin "small" under 3500 g, "medium" under 4500 g, otherwise "large".',
    setup: 'mass_g = 4000\n',
    given: '`mass_g` is already set. The fix is checked with several different masses.',
    buggy: 'if mass_g < 3500:\n    size = "small"\nelif mass_g > 4500:\n    size = "medium"\nelse:\n    size = "large"\n',
    fixed: 'if mass_g < 3500:\n    size = "small"\nelif mass_g < 4500:\n    size = "medium"\nelse:\n    size = "large"\n',
    bugLines: [3],
    tests: `for mass, want in [(3000, "small"), (4000, "medium"), (4500, "large"), (6000, "large")]:
    got = rerun(mass_g=mass)["size"]
    assert got == want, f"{mass} g should be {want!r}, but got {got!r}."`,
    explain: 'The middle case compared the wrong way. After ruling out "small", anything under 4500 is "medium".',
  },
  {
    id: 'pz-sort-none',
    title: 'Sorted into nothing',
    rating: 1000,
    concepts: ['lists', 'sorting'],
    task: 'Make a list of the masses, heaviest first.',
    buggy: 'masses = [3750, 3800, 3250]\nordered = masses.sort(reverse=True)\nprint(ordered)\n',
    fixed: 'masses = [3750, 3800, 3250]\nordered = sorted(masses, reverse=True)\nprint(ordered)\n',
    bugLines: [2],
    tests: 'assert ordered == [3800, 3750, 3250], f"ordered should be [3800, 3750, 3250], but it is {ordered}."',
    explain: '`.sort()` sorts in place and returns None. `sorted()` returns a new list.',
  },
  {
    id: 'pz-range-skip-first',
    title: 'Missing someone',
    rating: 1050,
    concepts: ['loops', 'range', 'indexing'],
    task: 'Add up the masses using their positions.',
    buggy: 'masses = [3750, 3800, 3250]\ntotal = 0\nfor i in range(1, len(masses)):\n    total += masses[i]\nprint(total)\n',
    fixed: 'masses = [3750, 3800, 3250]\ntotal = 0\nfor i in range(len(masses)):\n    total += masses[i]\nprint(total)\n',
    bugLines: [3],
    tests: 'assert total == 10800, f"total should be 10800, but it is {total}."',
    explain: 'Indexes start at 0, so `range(1, ...)` skipped the first penguin. `range(len(masses))` covers them all (or just loop over the list directly).',
  },
  {
    id: 'pz-print-not-return',
    title: 'Printed, not returned',
    rating: 1100,
    concepts: ['functions', 'return'],
    task: 'Convert two masses to kilograms and add them up.',
    buggy: 'def to_kg(mass_g):\n    print(mass_g / 1000)\n\ntotal = to_kg(3750) + to_kg(3800)\nprint(total)\n',
    fixed: 'def to_kg(mass_g):\n    return mass_g / 1000\n\ntotal = to_kg(3750) + to_kg(3800)\nprint(total)\n',
    bugLines: [2],
    tests: 'assert abs(total - 7.55) < 1e-9, f"total should be 7.55, but it is {total}."',
    explain: "`print` shows a value but the function still returns None, and None + None is a TypeError. Functions hand values back with `return`.",
  },
  {
    id: 'pz-expression-no-effect',
    title: 'A calculation that goes nowhere',
    rating: 1200,
    concepts: ['functions', 'variables'],
    task: 'Record two sightings, so count ends up as 2.',
    buggy: 'count = 0\n\ndef record(count):\n    count + 1\n    return count\n\ncount = record(count)\ncount = record(count)\nprint(count)\n',
    fixed: 'count = 0\n\ndef record(count):\n    count += 1\n    return count\n\ncount = record(count)\ncount = record(count)\nprint(count)\n',
    bugLines: [4],
    tests: 'assert count == 2, f"count should be 2, but it is {count}."',
    explain: '`count + 1` calculates a value and throws it away. To change the variable you need `count += 1` (or `count = count + 1`).',
  },
  {
    id: 'pz-return-in-loop',
    title: 'Leaving early',
    rating: 1250,
    concepts: ['functions', 'loops', 'indentation'],
    task: 'A function that adds up a list of masses.',
    buggy: 'def total_mass(masses):\n    total = 0\n    for m in masses:\n        total += m\n        return total\n\nprint(total_mass([3750, 3800, 3250]))\n',
    fixed: 'def total_mass(masses):\n    total = 0\n    for m in masses:\n        total += m\n    return total\n\nprint(total_mass([3750, 3800, 3250]))\n',
    bugLines: [5],
    tests: 'assert total_mass([1, 2, 3]) == 6, "total_mass([1, 2, 3]) should be 6."\nassert total_mass([]) == 0, "total_mass([]) should be 0."',
    explain: '`return` ends the function immediately. Indented inside the loop, it returned after the first item.',
  },
  {
    id: 'pz-split-spaces',
    title: 'Sneaky spaces',
    rating: 1300,
    concepts: ['strings', 'split'],
    task: 'Turn "Torgersen, Biscoe, Dream" into a list of island names.',
    buggy: 'text = "Torgersen, Biscoe, Dream"\nislands = text.split(",")\nprint(islands)\n',
    fixed: 'text = "Torgersen, Biscoe, Dream"\nislands = text.split(", ")\nprint(islands)\n',
    bugLines: [2],
    tests: 'assert islands == ["Torgersen", "Biscoe", "Dream"], f"Expected [\'Torgersen\', \'Biscoe\', \'Dream\'], but got {islands}."',
    explain: 'Splitting on "," leaves the space that follows each comma, giving " Biscoe". Split on ", " (or strip each part).',
  },
  {
    id: 'pz-text-sort',
    title: 'Alphabetical numbers',
    rating: 1350,
    concepts: ['sorting', 'types'],
    task: 'Readings arrived as text. Sort them from smallest to largest.',
    buggy: 'readings = ["900", "1200", "350"]\nordered = sorted(readings)\nprint(ordered)\n',
    fixed: 'readings = ["900", "1200", "350"]\nordered = sorted(readings, key=int)\nprint(ordered)\n',
    bugLines: [2],
    tests: 'assert [int(x) for x in ordered] == [350, 900, 1200], f"Expected the order 350, 900, 1200, but got {ordered}."',
    explain: 'Strings sort character by character, so "1200" comes before "350" (because "1" < "3"). Sort them as numbers with `key=int`, or convert them first.',
  },
  {
    id: 'pz-alias-copy',
    title: 'Two names, one list',
    rating: 1400,
    concepts: ['lists', 'references'],
    task: 'Make a kilogram copy of the masses, keeping the original list in grams.',
    buggy: 'original = [3750, 3800, 3250]\nconverted = original\nfor i in range(len(converted)):\n    converted[i] = converted[i] / 1000\nprint(original, converted)\n',
    fixed: 'original = [3750, 3800, 3250]\nconverted = original.copy()\nfor i in range(len(converted)):\n    converted[i] = converted[i] / 1000\nprint(original, converted)\n',
    bugLines: [2],
    tests: 'assert original == [3750, 3800, 3250], f"original should still be in grams, but it is {original}."\nassert converted == [3.75, 3.8, 3.25], f"converted should be in kg, but it is {converted}."',
    explain: '`converted = original` doesn\'t copy anything: both names point to the same list, so changing one changes "both". Use `.copy()`.',
  },
  {
    id: 'pz-empty-average',
    title: 'The empty case',
    rating: 1450,
    concepts: ['functions', 'edge cases'],
    task: 'Average a list of values, returning 0 for an empty list.',
    buggy: 'def average(values):\n    if len(values) == 1:\n        return 0\n    return sum(values) / len(values)\n',
    fixed: 'def average(values):\n    if len(values) == 0:\n        return 0\n    return sum(values) / len(values)\n',
    bugLines: [2],
    tests: 'assert average([]) == 0, "average([]) should return 0."\nassert average([2, 4]) == 3, "average([2, 4]) should be 3."\nassert average([5]) == 5, "average([5]) should be 5, not 0."',
    explain: 'The guard checked for one item instead of zero, so a single value returned 0 and an empty list crashed with ZeroDivisionError.',
  },
  {
    id: 'pz-float-equal',
    title: 'Almost exactly',
    rating: 1550,
    concepts: ['floats', 'comparison'],
    task: 'Check whether the shares of three species add up to 1 (100%).',
    buggy: 'shares = [0.7, 0.2, 0.1]\ntotal = shares[0] + shares[1] + shares[2]\nis_complete = total == 1.0\nprint(is_complete)\n',
    fixed: 'shares = [0.7, 0.2, 0.1]\ntotal = shares[0] + shares[1] + shares[2]\nis_complete = abs(total - 1.0) < 1e-9\nprint(is_complete)\n',
    bugLines: [3],
    tests: 'assert is_complete is True, "These shares add up to 1, so is_complete should be True."',
    explain: 'Floats are stored in binary, so 0.1 + 0.2 + ... can land a tiny bit away from 1.0. Compare floats with a tolerance (or `math.isclose`), never with `==`.',
  },
  {
    id: 'pz-mutable-default',
    title: 'The list that remembers',
    rating: 1700,
    concepts: ['functions', 'defaults', 'lists'],
    task: 'Start a new log for each call, unless a log is passed in.',
    buggy: 'def new_log(value, readings=[]):\n    if readings is None:\n        readings = []\n    readings.append(value)\n    return readings\n\nday1 = new_log(181)\nday2 = new_log(186)\nprint(day1, day2)\n',
    fixed: 'def new_log(value, readings=None):\n    if readings is None:\n        readings = []\n    readings.append(value)\n    return readings\n\nday1 = new_log(181)\nday2 = new_log(186)\nprint(day1, day2)\n',
    bugLines: [1],
    tests: 'assert day1 == [181], f"day1 should be [181], but it is {day1}."\nassert day2 == [186], f"day2 should be [186], but it is {day2}."',
    explain: 'A default value is created once, when the function is defined, so every call shared the same list. Default to None and create the list inside, which the code already tried to do.',
  },
  {
    id: 'pz-remove-while-looping',
    title: 'Pulling the rug',
    rating: 1800,
    concepts: ['lists', 'loops'],
    task: 'Remove every missing value (None) from the list.',
    buggy: 'masses = [3750, None, None, 3250, None]\nfor m in masses:\n    if m is None:\n        masses.remove(m)\nprint(masses)\n',
    fixed: 'masses = [3750, None, None, 3250, None]\nfor m in masses[:]:\n    if m is None:\n        masses.remove(m)\nprint(masses)\n',
    bugLines: [2],
    tests: 'assert masses == [3750, 3250], f"Expected [3750, 3250], but got {masses}."',
    explain: 'Removing items from a list while looping over it shifts everything left, so the loop skips the item after each removal. Loop over a copy (`masses[:]`), or build a new list instead.',
  },
];
